[project]
name = "ofrep-validator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "rich>=14.1.0",
    "typer>=0.19.2",
]

[project.scripts]
ofrep-validator = "main:app"
